name: ✏️ Design
description: "Submit a proposal for a new design"
title: "✏️ Design: "
labels: [design]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our design request form 🙏
  - type: textarea
    id: design-description
    validations:
      required: true
    attributes:
      label: "🔖 Feature description"
      description: "A clear and concise description of what the feature is."
      placeholder: "You should add ..."
